[package]
name = "aoc19"
version = "0.1.0"
authors = ["nils måsén <nils@piksel.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "aoc19"
path = "main.rs"
